# ci croco
# check this file with: https://gitlab.inria.fr/ci/lint

variables:
  TERM: "xterm-256color"
  CVTKHOME: "$CI_PROJECT_DIR/CVTK/test_repro/CVTK_DEBUG_FAST_src"
  PERFRSTHOME: "$CI_PROJECT_DIR/CVTK/test_perfrst/src"
  DATADIR: "$CI_PROJECT_DIR/.datadir"
  PERFRSTDIR: "$CI_PROJECT_DIR/.perfrstdir"
  CVTKWORK: "$CI_PROJECT_DIR/.datawork"
  PERFRSTWORK: "$CI_PROJECT_DIR/.perfrstwork"
  CROCO_CI_MPIRUN: "mpirun.openmpi"
  
  
before_script:
  - mkdir -p $DATADIR
  - mkdir -p $CVTKWORK
  - cd $DATADIR
  - mkdir -p TESTROOT/REG
  - mkdir -p $PERFRSTDIR
  - mkdir -p $PERFRSTWORK
  - cd $PERFRSTDIR
  - mkdir -p TESTROOT/REG
    
reg_run:
  only:
    - schedules  
  script:
    - cd $CVTKHOME/Scripts_reg
    - ./create_link_master_reg.sh
    - cd -
    - cd $CVTKWORK/REG
  
    - ./mk_TESTALL.bash CONFIGURE_REG reg
    - ./gather_recap.bash REG > /dev/null 2>&1
    - /bin/sh -c '! grep -i "Compilation failure" REG_gather_recap_*_git*' > /dev/null 2>&1
    - /bin/sh -c '! grep -i "Execution failure" REG_gather_recap_*_git*' > /dev/null 2>&1
    - /bin/sh -c '! grep -i "Parallel reproducibility failed" REG_gather_recap_*_git*' > /dev/null 2>&1

reg_perfrst:
  only:
    - schedules  
  script:
    - cd $PERFRSTHOME/Scripts_reg_perfrst
    - ./create_link_master_reg_perfrst.sh
    - cd -
    - cd $PERFRSTWORK/REG
    
    - ./mk_TESTALL.bash CONFIGURE_REG_PERFRST reg
    - ./gather_recap_perfrst.bash REG > /dev/null 2>&1
    - /bin/sh -c '! grep -i "Compilation failure" REG_gather_recap_*_git*' > /dev/null 2>&1
    - /bin/sh -c '! grep -i "Execution failure" REG_gather_recap_*_git*' > /dev/null 2>&1
    - /bin/sh -c '! grep -i "Restartabilty failed" REG_gather_recap_*_git*' > /dev/null 2>&1

  artifacts:
    paths:
      - $PERFRSTWORK/ftp
    when: always

